/**
		
	Do not edit this file. It's generated automatically from template/acceptance.tests.template.
		
*/
define(function(require) {
    var feature = require('text!acceptance/feature/load.feature');
    var world = require('acceptance/helper/world');
    var steps = require('acceptance/step/load.steps');

    return {
        supportCode: function() {
            world.bind(this)();
            steps.bind(this)();
        },
        features: feature
    }
});